### ISSUE TITLE
code generate from swagger.json to request_api.py

### ISSUE THREAD

**Issue by DediBar** [Sean-Bradley/Seans-Python3-Flask-Rest-Boilerplate#2]
Hi 
Great project ;-)
Is there way to perform code generate from swagger.json to request_api.py ?

Thank you

**Comment by Sean-Bradley** [comment]
This is not an issue, read the license, no warranty etc , pay me if you want me to do something for you

**Comment by DediBar** [comment]
Hi 
What is your email ?
